### ISSUE TITLE
Discrepancy in target color when met/unmet

### ISSUE THREAD

**Issue by jamcgowan-SCP** [andrewcottam/marxan-web#109]
See image. By my understanding, the pink ones for substrates should be clear becuase the target was met. 

<img width="382" alt="Screen Shot 2019-12-11 at 11 34 36 am" src="https://user-images.githubusercontent.com/52007548/70614153-4de00880-1c0a-11ea-8803-7ea199ecf64d.png">

**Comment by andrewcottam** [comment]
When you run BC example with 100 iterations
