### ISSUE TITLE
Windows installation with PostgreSQL already installed.

### ISSUE THREAD

**Issue by ricschuster** [andrewcottam/marxan-web#69]
I installed marxan-web on a Windows machine with a PostgreSQL version (9.6) already installed. 
After install had finished, the login screen did not disappear after registering user and subsequently login in (Win10, Chrome 77)
Error: Execution failed on sql 'SELECT feature_class_name ,alias ,description ,creation_date::text ,country_id   

I uninstalled both PostgreSQL and marxan-web, rebotted and installed marxan-web again. Now the login works.

**Comment by andrewcottam** [comment]
When you installed the first time, did you tick/untick the install PostGIS stuff:
![install](https://user-images.githubusercontent.com/596494/64844154-4909b980-d607-11e9-890a-9a478c2894d8.png)

**Comment by ricschuster** [comment]
The PostGIS install was ticked (by default) and I left it at that.
I don't remember seeing the PostGIS server settings section though.

**Comment by andrewcottam** [comment]
Sorry - confusing screenshot. To use your own existing db, untick the box - not like above :)

**Comment by ricschuster** [comment]
Oh, I get it now. Thanks
