### ISSUE TITLE
Allow to split uploaded shapefile into features

### ISSUE THREAD

**Issue by ricschuster** [andrewcottam/marxan-web#91]
I just uploaded a shapefile (AUT_mammals), which has 95 polygons, each being a feature. It looks like the entire shapefile is currently one feature and I don't see a way to split this shapefile up into features. Needing to upload one shapefile per feature seems not ideal to me. 

Can a number of shapefiles be uploaded as one zip file?

Ideally, it would be great to upload one shapefile that can then be processed into individual features, base on attributes that a user can choose.

**Comment by andrewcottam** [comment]
This is a great idea and links to #85 - I could add new items on the Import button. One for import single feature and another for import multiple features and allow the user to specify a field for the species name. Would that work?

**Comment by ricschuster** [comment]
That would be great! Thanks Andrew.

**Comment by andrewcottam** [comment]
Added it as a feature and will update the beta site tomorrow.
